### ISSUE TITLE
Passing Specific step name to this action

### ISSUE THREAD

**Issue by AdityaHitachi** [sergioaten/msteams-notifications#1]
If we want to track only specific steps in the workflow, Is there any way to pass specific step names to this action instead of this 
 `steps: ${{ toJson(steps) }}`?

**Comment by sergioaten** [comment]
The action only catch the steps which have "id" parameter.
✔️ Step which show in notifications report: 
```
- name: Example step
  id: example
  run: |
    echo "Hello world!"`
```

❌ Step which dont show in notifications report: 
```
- name: Example step
  run: |
    echo "Hello world!"`
```

If this dont solve your issue, tell me what do u need. 🙂

Regards!
